# Generated by Django 6.0.1 on 2026-03-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=64)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visit_date', 'session_key'), name='unique_daily_session_visit')],
            },
        ),
    ]
