# Generated by Django 6.0.1 on 2026-03-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_sitevisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'verbose_name': 'Відвідування сайту', 'verbose_name_plural': 'Відвідування сайту'},
        ),
    ]
