# Generated by Django 6.0.1 on 2026-03-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_sitevisit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='path',
        ),
    ]
