# Generated by Django 6.0.1 on 2026-03-31 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_sitevisit_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Виберіть батьківську категорію (якщо це підкатегорія)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category'),
        ),
    ]
