# Generated by Django 6.0.1 on 2026-04-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hex_color', models.CharField(default='#9CA3AF', help_text='Цвет вкуса в hex формате (например, #FF5733)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Количество в наличии для этого вкуса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.flavor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='shop.product')),
            ],
            options={
                'ordering': ['flavor__name'],
                'unique_together': {('product', 'flavor')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='shop.productflavor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productflavor'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('customer', 'product', 'flavor')},
        ),
    ]
