# Generated by Django 6.0.1 on 2026-04-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_flavor_productflavor_cartitem_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=50, help_text='Кількість в наявності (використовується тільки якщо немає смаків)'),
        ),
    ]
