# Generated by Django 6.0.1 on 2026-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_gift',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='flavor',
            name='hex_color',
            field=models.CharField(default='#9CA3AF', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стара ціна', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Кількість в наявності (використовується тільки якщо немає смаків)'),
        ),
        migrations.AlterField(
            model_name='productflavor',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
