# Generated by Django 6.0.1 on 2026-04-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='description',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення (менше = раніше)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='shop.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
