# Generated by Django 6.0.1 on 2026-04-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_flavor_description_add_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Видаляємо старі відповіді бо їх admin_id посилається на Customer, а не на auth.User
        migrations.RunSQL(
            "DELETE FROM shop_reviewreply;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
