# Generated by Django 6.0.1 on 2026-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
