# Generated by Django 6.0.1 on 2026-04-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_flavor_name_max_length_30'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='flavor',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_label', models.CharField(blank=True, default='', help_text='Грамовка, наприклад: 500г, 1кг', max_length=20)),
                ('weight_grams', models.PositiveIntegerField(default=0, help_text='Вага в грамах для сортування')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.flavor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'ordering': ['weight_grams', 'weight_label', 'flavor__name'],
                'unique_together': {('product', 'weight_label', 'flavor')},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='cartitem',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('customer', 'product', 'variant')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='flavor',
        ),
    ]
