# Generated by Django 6.0.1 on 2026-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_orderitem_flavor_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стара ціна (якщо є знижка)', max_digits=10, null=True),
        ),
    ]
