# Generated by Django 6.0.1 on 2026-04-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_productvariant_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
