# Generated by Django 6.0.1 on 2026-04-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_add_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_admin',
        ),
    ]
