# Generated by Django 6.0.1 on 2026-04-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_customer_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFlavor',
        ),
    ]
