# Generated by Django 6.0.1 on 2026-04-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_productflavor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['order', 'weight_label', 'flavor__name']},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight_grams',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок відображення (менше = раніше)'),
        ),
    ]
