# Generated by Django 6.0.1 on 2026-04-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_replace_weight_grams_with_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='order',
        ),
    ]
